# Site settings
title: CodeNugget
keywords: "blog, tech, apple, mobile, dev, development, ios, web, nodejs, swift, objective-c, cocoa"
description: > # this means to ignore newlines until "baseurl:"
  Pascal Cremer is Engineering Lead at trivago, the world leading hotel search engine, based in Düsseldorf, Germany. He cares about technology as much as building amazing teams, and creating great synergies.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://codenugget.co" # the base hostname & protocol for your site
email: hello@codenugget.co
twitter_username: b00gizm
github_username:  b00gizm
ga_id: UA-37998016-1

# Build settings
markdown: kramdown
exclude: ['Gemfile', 'Gemfile.lock', 'vendor', 'puppet']

# Kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Redcarpet
redcarpet:
  extensions: [
    'footnotes'
  ]

# Gems
gems:
  - jekyll-gist

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "default"
