# Site settings
title: CodeNugget
keywords: "blog, tech, apple, mobile, dev, development, ios, web, nodejs, swift, objective-c, cocoa"
description: > # this means to ignore newlines until "baseurl:"
  Hi. I'm Pascal. I work as a senior developer at <a href="http://chefkoch.de">Chefkoch.de</a>, Europe's biggest 
  cooking platform, and this is my persional blog "Codenugget".
  
  CodeNugget is all about web and mobile (iOS) development, workflow automation,
  interesting bits of tech news, and the overall digital lifestyle.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://codenugget.co" # the base hostname & protocol for your site
email: hello@codenugget.co
twitter_username: b00gizm
github_username:  b00gizm
ga_id: UA-37998016-1

# Build settings
markdown: redcarpet
exclude: ['Gemfile', 'Gemfile.lock', 'vendor', 'puppet']

# Redcarpet
redcarpet:
  extensions: [
    'footnotes'
  ]

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "default"
